server:
  port: 51601
spring:
  application:
    name: leadnews-app-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        - id: user
          uri: http://localhost:51801
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1
        - id: article
          uri: http://localhost:51802
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix= 1
        - id: search
          uri: http://localhost:51804
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix= 1
        - id: behavior
          uri: http://localhost:51805
          predicates:
            - Path=/behavior/**
          filters:
            - StripPrefix= 1