server:
  port: 6001
spring:
  application:
    name: leadnews-admin-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        - id: admin
          uri: http://localhost:51805
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix= 1
        - id: user
          uri: http://localhost:51801
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1
        - id: article
          uri: http://localhost:51802
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix= 1
        - id: wemedia
          uri: http://localhost:51803
          predicates:
            - Path=/wemedia/**
          filters:
            - StripPrefix= 1
