server:
  port: 51803
spring:
  application:
    name: leadnews-wemedia
  cloud:
    discovery:
      client:
        simple:
          instances:
            leadnews-article:
              - uri: http://localhost:51802
            leadnews-schedule:
              - uri: http://localhost:51701
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_wemedia?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 707161
  kafka:
    bootstrap-servers: 172.0.10.2:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.qiao.model.wemedia.pojos

minio:
  accessKey: minio
  secretKey: minio123
  bucket: leadnews
  endpoint: http://172.0.10.2:9000
  readPath: http://172.0.10.2:9000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

tess4j:
  data-path: D:\\Qiao\\leadnews
  language: chi_sim