server:
  port: 8881
spring:
  application:
    name: test-freemarker
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
    suffix: .ftl
    template-loader-path: classpath:/templates